<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Surihix</Company>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <FileVersion>1.0.0.1</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <Copyright>Copyright © Surihix 2026</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
